name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Push Docker image to Docker Hub
      run: |
        echo "${{ secrets.Deveshdocker08 }}" | docker login -u "${{ secrets.deveshraj08 }}" --password-stdin
        docker tag my-image-name:$(date +%s) my-dockerhub-username/my-image-name:latest
        docker push my-dockerhub-username/my-image-name:latest

